name: jobs 

on:
  workflow_dispatch:
  
jobs:
  build-job:
    container: oven/bun:slim
    outputs:
      build-output: ${{ steps.buildStep.outputs.buildOut }}
    name: build job
    runs-on: ubuntu-latest
    steps:
      - name: Define output variable
        id: buildStep
        run: |
          bunver=$(bun --version)
          echo "buildOut=$bunver" >> "$GITHUB_OUTPUT"
       #run: echo "buildOut=This is a variable from job 1" >> "$GITHUB_OUTPUT"
  deploy-job:
    #if: ${{ fromJSON(needs.build-job.outputs.build-output) > 1 }}
    name: deploy job
    runs-on: ubuntu-latest
    needs: build-job
    steps:
      - name: test build variable
        #run: echo ${{ fromJSON(needs.build-job.outputs.build-output) }}
        #if: contains(needs.build-job.outputs.build-output, 'job' )
        run: echo ${{ needs.build-job.outputs.build-output }}
  concurrency-job1:
    runs-on: ubuntu-latest
    concurrency:
      group: testing
    steps:
      - run: echo job1
  concurrency-job2:
    runs-on: ubuntu-latest
    concurrency:
      group: testing
    steps:
      - run: echo job2
      
    
  
  #test-job:
    #name: testing
   # runs-on: ubuntu-latest
    #steps:
    #  - name: unit testing and linting
      #  id: testStep
     #   run: echo testing

#  container-scanning:
  #  #image: 
  #  name: scan the container image
  #  runs-on: ubuntu-latest
