name: jobs 

on:
  workflow_dispatch:
  
jobs:
  build-job:
    #image: 
    outputs:
      build-output: ${{ steps.buildStep.outputs.buildOut }}
    name: build job
    runs-on: ubuntu-latest
    steps:
      - name: Define output variable
        id: buildStep
        run: echo "buildOut=This is a variable from job 1" >> "$GITHUB_OUTPUT"
  deploy-job:
    name: deploy job
    runs-on: ubuntu-latest
    needs: build-job
    steps:
      - name: test build variable
        if: ${{ contains(needs.build-job.outputs.build-output, 'job' }}
        run: echo ${{ jobs.build-job.outputs.build-output }}
      
    
  
  #test-job:
    #name: testing
   # runs-on: ubuntu-latest
    #steps:
    #  - name: unit testing and linting
      #  id: testStep
     #   run: echo testing

#  container-scanning:
  #  #image: 
  #  name: scan the container image
  #  runs-on: ubuntu-latest
